### PR TITLE
Major cleanup (such as PEP8 et al, see details in CHANGES.rst)

### PR DESCRIPTION
**Pull request by jensens**
This is a real huge cleanup. The old tests are running local with the overhauled integrated buildout.
Now lets see if it runs on jenkins with coredev as well.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Was Jenkins running anywhere? Note that sources.cfg in core-dev still points to the zopefoundation repo.

I started reviewing this, but with so many changes this is basically impossible.  It looked okay to me, but github could not even display the entire diff.

I have created pull request #2 with the exact same code, but with autopep8 changes in separate commits. A `git diff maurits-cleanup jensens-pep8-and-cleanup` locally gives no differences between the two branches.

**Comment by jensens** [comment]
I did not touch any application logic. And yes the old code was old and had a very special formatting - completly not pep8, difficult to read.

So I changed coredev 5 sources.cfg to use the plone PAS master for now. 

test runs here: http://jenkins.plone.org/job/pull-request-5.0/492/

**Comment by jensens** [comment]
looks like short before commit something went wrong. Now reverted the wrong change and test again.
http://jenkins.plone.org/job/pull-request-5.0/493/

**Comment by jensens** [comment]
ok, all plone tests are passing with this PR. All PAS tests are passing too. I'd say this beast is ready. 

cc @esteele

**Comment by jensens** [comment]
close here, #2 has better commits

**Pull request closed without merging**
